# action.yml
name: 'Hello World action example by deepakgc'
description: 'Greet someone and record the time'
branding:
  icon: 'award'
  color: 'green'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  To pass inputs to the Docker container, you must declare the input using inputs and pass the input in the args keyword.
  args:
  - ${{ inputs.who-to-greet }}
